# TCL File Generated by Component Editor 18.1
# Wed Mar 19 14:34:56 EDT 2025
# DO NOT MODIFY


# 
# custom_ip "custom_ip" v1.0
# Ryan Salmon 2025.03.19.14:34:56
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module custom_ip
# 
set_module_property DESCRIPTION ""
set_module_property NAME custom_ip
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Ryan Salmon"
set_module_property DISPLAY_NAME custom_ip
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL servo_controller
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file servo_controller.vhd VHDL PATH servo_controller.vhd TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter iterator STRING 000111110100
set_parameter_property iterator DEFAULT_VALUE 000111110100
set_parameter_property iterator DISPLAY_NAME iterator
set_parameter_property iterator TYPE STRING
set_parameter_property iterator UNITS None
set_parameter_property iterator HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock clock
set_interface_property conduit_end associatedReset reset
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end outwave outwave Output 1


# 
# connection point interrupt_sender
# 
add_interface interrupt_sender interrupt end
set_interface_property interrupt_sender associatedAddressablePoint avalon_slave_0_1
set_interface_property interrupt_sender associatedClock clock
set_interface_property interrupt_sender associatedReset reset
set_interface_property interrupt_sender bridgedReceiverOffset ""
set_interface_property interrupt_sender bridgesToReceiver ""
set_interface_property interrupt_sender ENABLED true
set_interface_property interrupt_sender EXPORT_OF ""
set_interface_property interrupt_sender PORT_NAME_MAP ""
set_interface_property interrupt_sender CMSIS_SVD_VARIABLES ""
set_interface_property interrupt_sender SVD_ADDRESS_GROUP ""

add_interface_port interrupt_sender IRQ irq Output 1


# 
# connection point avalon_slave_0_1
# 
add_interface avalon_slave_0_1 avalon end
set_interface_property avalon_slave_0_1 addressUnits WORDS
set_interface_property avalon_slave_0_1 associatedClock clock
set_interface_property avalon_slave_0_1 associatedReset reset
set_interface_property avalon_slave_0_1 bitsPerSymbol 8
set_interface_property avalon_slave_0_1 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0_1 burstcountUnits WORDS
set_interface_property avalon_slave_0_1 explicitAddressSpan 0
set_interface_property avalon_slave_0_1 holdTime 0
set_interface_property avalon_slave_0_1 linewrapBursts false
set_interface_property avalon_slave_0_1 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0_1 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0_1 readLatency 0
set_interface_property avalon_slave_0_1 readWaitTime 1
set_interface_property avalon_slave_0_1 setupTime 0
set_interface_property avalon_slave_0_1 timingUnits Cycles
set_interface_property avalon_slave_0_1 writeWaitTime 0
set_interface_property avalon_slave_0_1 ENABLED true
set_interface_property avalon_slave_0_1 EXPORT_OF ""
set_interface_property avalon_slave_0_1 PORT_NAME_MAP ""
set_interface_property avalon_slave_0_1 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0_1 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0_1 we write Input 1
add_interface_port avalon_slave_0_1 w_data writedata Input 32
add_interface_port avalon_slave_0_1 addr address Input 1
set_interface_assignment avalon_slave_0_1 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0_1 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0_1 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0_1 embeddedsw.configuration.isPrintableDevice 0

